FROM centos:7

ARG DBSERVER
ARG MEMSERVER
ARG TELNETMA2

RUN yum -y install gcc epel-release mod_ssl && \
    yum -y install cpan \
     perl-DBI \
     perl-DBD-MySQL \
     perl-JSON \
     perl-Archive-Zip \
     perl-Test-Simple \
     perl-Digest-MD5 \
     perl-ExtUtils-MakeMaker \
     perl-libwww-perl \
     perl-LWP-Protocol-https \
     perl-Crypt-SSLeay \
     perl-Crypt-CBC \
     perl-Cache-Memcached && \
    yum clean all && \
    echo q | /usr/bin/perl -MCPAN -e shell && \
    cpan -f URI::Escape::JavaScript && \
    cpan -f Crypt::Blowfish && \
    rm -rf /root/.cpan && \
    \cp -f /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    /usr/sbin/adduser -u 2323 -g root telnetman && \
    echo telnetman:tcpport23 | chpasswd && \
    mkdir /usr/local/TelnetmanWF && \
    mkdir /usr/local/TelnetmanWF/lib && \
    mkdir /usr/local/TelnetmanWF/pl && \
    mkdir /var/TelnetmanWF

ADD ./lib/*  /usr/local/TelnetmanWF/lib/
ADD ./pl/*   /usr/local/TelnetmanWF/pl/
ADD ./install/logrotate.sh /usr/local/bin/logrotate.sh

RUN sed -i -e "s/localhost/$DBSERVER/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/'telnetman', 'tcpport23'/'root', ''/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/192\.168\.203\.96/$TELNETMA2:8443/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/127\.0\.0\.1/$MEMSERVER/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    chown -R telnetman:root /var/TelnetmanWF && \
    chmod -R 775 /var/TelnetmanWF && \
    chmod 644 /usr/local/TelnetmanWF/lib/* && \
    chmod 644 /usr/local/TelnetmanWF/pl/*

USER telnetman
