FROM centos:7

ARG DBSERVER
ARG WEBSERVER
ARG TELNETMA2
ARG TELNETMA2_PORT

RUN yum -y install gcc epel-release mod_ssl cronie logrotate && \
    yum -y install cpan \
     perl-DBI \
     perl-DBD-MySQL \
     perl-JSON \
     perl-Archive-Zip \
     perl-Test-Simple \
     perl-Digest-MD5 \
     perl-ExtUtils-MakeMaker \
     perl-libwww-perl \
     perl-LWP-Protocol-https \
     perl-Crypt-SSLeay \
     perl-Crypt-CBC \
     perl-Cache-Memcached && \
    yum clean all && \
    echo q | /usr/bin/perl -MCPAN -e shell && \
    cpan -f URI::Escape::JavaScript && \
    cpan -f Crypt::Blowfish && \
    rm -rf /root/.cpan && \
    \cp -f /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    /usr/sbin/adduser -u 2323 -g root telnetman && \
    echo telnetman:tcpport23 | chpasswd && \
    mkdir /usr/local/TelnetmanWF && \
    mkdir /usr/local/TelnetmanWF/lib && \
    mkdir /usr/local/TelnetmanWF/pl && \
    mkdir /var/TelnetmanWF

ADD ./lib/*  /usr/local/TelnetmanWF/lib/
ADD ./pl/*   /usr/local/TelnetmanWF/pl/
ADD ./install/TelnetmanWF.cron /etc/cron.d/TelnetmanWF.cron
ADD ./install/TelnetmanWF.logrotate.txt /etc/logrotate.d/TelnetmanWF

RUN sed -i -e "s/localhost/$DBSERVER/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/'telnetman', 'tcpport23'/'root', ''/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/192\.168\.203\.96/$TELNETMA2:$TELNETMA2_PORT/" /usr/local/TelnetmanWF/lib/Common_system.pm && \
    sed -i -e "s/127\.0\.0\.1/$WEBSERVER/" /usr/local/TelnetmanWF/pl/check_status.pl && \
    chown -R telnetman:root /var/TelnetmanWF && \
    chmod -R 775 /var/TelnetmanWF && \
    chmod 644 /usr/local/TelnetmanWF/lib/* && \
    chmod 644 /usr/local/TelnetmanWF/pl/* && \
    sed -i -e "s/apache/telnetman/g" /etc/cron.d/TelnetmanWF.cron && \
    chown root:root /etc/cron.d/TelnetmanWF.cron && \
    chmod 644 /etc/cron.d/TelnetmanWF.cron && \
    chown root:root /etc/logrotate.d/TelnetmanWF && \
    chmod 644 /etc/logrotate.d/TelnetmanWF

ADD ./install/start-cron.sh /sbin/start.sh

CMD ["sh", "/sbin/start.sh"]
